
const employeesToUpdate = [
  { surname: 'Talaban', firstName: 'Babelyn', position: 'MSWDO', salary: '80,648.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Lacuarta', firstName: 'Jerry', position: 'Soc. Welfare Asst.', salary: '18,456.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Villoza', firstName: 'Pamela', position: 'Soc. Welfare Asst. II', salary: '17,645.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Arteza', firstName: 'Jeanny', position: 'Soc. Welfare Aide', salary: '13,845.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Laz', firstName: 'Jose', position: 'Adm. Aide III', salary: '12,941.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Palomo', firstName: 'Frankie', position: 'Adm. Aide III', salary: '12,843.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Diaz', firstName: 'Frank', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Moaña', firstName: 'Neisa', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Mesias', firstName: 'Sallie', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Dela Cruz', firstName: 'Joselito', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Galapia', firstName: 'Jackelyn', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Montorio', firstName: 'Desam', position: 'H.R.M.O V', salary: '79,382.00', station: 'Human Resource Management Office' },
  { surname: 'Golez', firstName: 'Maryjean', position: 'Adm. Aide IV', salary: '14,373.00', station: 'Human Resource Management Office' },
  { surname: 'Alcjado', firstName: 'Shanie', position: 'Adm. Aide II', salary: '12,092.00', station: 'Human Resource Management Office' },
  { surname: 'Baldonado', firstName: 'Joselito', position: 'Adm. Aide I', salary: '11,662.00', station: 'Human Resource Management Office' },
  { surname: 'Andaya', firstName: 'Ma. Aurora', position: 'Mun. Civil Registrar', salary: '84,577.00', station: 'Local Civil Registry Office' },
  { surname: 'Mesias', firstName: 'Erlinda', position: 'Messenger', salary: '12,274.00', station: 'Local Civil Registry Office' },
  { surname: 'Gregore', firstName: 'Erly', position: 'Adm. Aide I', salary: '11,567.00', station: 'Local Civil Registry Office' },
  { surname: 'Labo', firstName: 'Sharon', position: 'Adm. Aide I', salary: '11,473.00', station: 'Local Civil Registry Office' },
  { surname: 'Leonardo', firstName: 'Irene', position: 'Adm. Aide I', salary: '11,473.00', station: 'Local Civil Registry Office' },
  { surname: 'Letran', firstName: 'Angel', position: 'Adm. Aide I', salary: '11,388.00', station: 'Local Civil Registry Office' },
  { surname: 'Labo', firstName: 'Alejandre', position: 'Mun. Engineer', salary: '88,659.00', station: 'Municipal Engineering Office' },
  { surname: 'Labao', firstName: 'Rexjhon', position: 'MGADH I', salary: '63,153.00', station: 'Municipal Engineering Office' },
  { surname: 'Berganio', firstName: 'Karen', position: 'Engineer III', salary: '45,515.00', station: 'Municipal Engineering Office' },
  { surname: 'Dela Peña', firstName: 'Romuel', position: 'C/M foreman', salary: '24,399.00', station: 'Municipal Engineering Office' },
  { surname: 'Toledo', firstName: 'Gerbert', position: 'Gen. Foreman', salary: '17,496.00', station: 'Municipal Engineering Office' },
  { surname: 'Guion', firstName: 'Gerold', position: 'Adm. Aide I', salary: '11,951.00', station: 'Municipal Engineering Office' },
  { surname: 'Villareal', firstName: 'Gemma', position: 'Adm. Aide I', salary: '11,951.00', station: 'Municipal Engineering Office' },
  { surname: 'Puncion', firstName: 'Josephine', position: 'Adm. Aide I', salary: '11,662.00', station: 'Municipal Engineering Office' },
  { surname: 'Leno', firstName: 'Luna Rose', position: 'Adm. Aide I', salary: '11,567.00', station: 'Municipal Engineering Office' },
  { surname: 'Guatio', firstName: 'Rhodora', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Engineering Office' },
  { surname: 'Magbanua', firstName: 'Noe', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Engineering Office' },
  { surname: 'Osias', firstName: 'Ferdinand', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Engineering Office' },
  { surname: 'Gallardo', firstName: 'Amie', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Engineering Office' },
  { surname: 'Barte', firstName: 'Michel', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Engineering Office' },
  { surname: 'Ocbeña', firstName: 'Darenne', position: 'Adm. Aide I', salary: '11,854.00', station: 'Municipal Engineering Office' },
  { surname: 'Crisostomo', firstName: 'Mila', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Engineering Office' },
  { surname: 'Gregorio', firstName: 'Mica', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Engineering Office' },
  { surname: 'Lago', firstName: 'Teresa', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Engineering Office' },
  { surname: 'Buenavista', firstName: 'Richard', position: 'Mun. Vice Mayor', salary: '90,367.00', station: 'Office of the Vice Mayor / Sangguniang Bayan' },
  { surname: 'Labao', firstName: 'Mary Ann', position: 'S. B. Member', salary: '80,648.00', station: 'Sangguniang Bayan' },
  { surname: 'Villiester', firstName: 'Catherine', position: 'S. B. Member', salary: '80,648.00', station: 'Sangguniang Bayan' },
  { surname: 'Ticer', firstName: 'Raul', position: 'S. B. Member', salary: '79,382.00', station: 'Sangguniang Bayan' },
  { surname: 'Laurilla', firstName: 'John', position: 'S. B. Member', salary: '79,382.00', station: 'Sangguniang Bayan' },
  { surname: 'Trajano', firstName: 'Fatima', position: 'S. B. Member', salary: '79,382.00', station: 'Sangguniang Bayan' },
  { surname: 'Layo', firstName: 'Jeffrey', position: 'S. B. Member', salary: '79,382.00', station: 'Sangguniang Bayan' },
  { surname: 'Jumbas', firstName: 'Joefred sheen', position: 'S. B. Member', salary: '79,382.00', station: 'Sangguniang Bayan' },
  { surname: 'Uy', firstName: 'Maria Rhodora', position: 'S. B. Member', salary: '80,648.00', station: 'Sangguniang Bayan' },
  { surname: 'Quincy', firstName: 'George', position: 'ABC President', salary: '79,382.00', station: 'Sangguniang Bayan' },
  { surname: 'Buenavista', firstName: 'Frederick Ruis', position: 'SK President', salary: '79,382.00', station: 'Sangguniang Bayan' },
  { surname: 'Leonida', firstName: 'Jerry', position: 'SB Secretary', salary: '88,659.00', station: 'Office of the SB Secretary' },
  { surname: 'Bersurto', firstName: 'Irish Ann', position: 'Local Leg Staff Officer IV', salary: '45,515.00', station: 'Office of the SB Secretary' },
  { surname: 'Puncion', firstName: 'Che-An', position: 'Local Leg Staff Officer I', salary: '27,777.00', station: 'Office of the SB Secretary' },
  { surname: 'Ladoc', firstName: 'Mariane', position: 'Loc. Leg. Staff Asst. III', salary: '24,399.00', station: 'Office of the SB Secretary' },
  { surname: 'Benjamin', firstName: 'Vincent', position: 'Loc. Leg. Staff Asst. I', salary: '20,795.00', station: 'Office of the SB Secretary' },
  { surname: 'Benjamin', firstName: 'Ma. Cenneth', position: 'Loc. Leg. Staff Employee', salary: '15,359.00', station: 'Office of the SB Secretary' },
  { surname: 'Canique', firstName: 'Jinalyn', position: 'Loc. Leg. Staff Employee', salary: '13,741.00', station: 'Office of the SB Secretary' },
  { surname: 'Llorente', firstName: 'Christine Joy', position: 'Adm. aide III', salary: '12,941.00', station: 'Office of the SB Secretary' },
  { surname: 'Vpinosa', firstName: 'Levi', position: 'Adm. aide III', salary: '12,941.00', station: 'Office of the SB Secretary' },
  { surname: 'Labao', firstName: 'Hazel', position: 'Local Leg. Staff Employee', salary: '12,367.00', station: 'Office of the SB Secretary' },
  { surname: 'Labris', firstName: 'Jesa', position: 'Messenger', salary: '12,274.00', station: 'Office of the SB Secretary' },
  { surname: 'Palma', firstName: 'Criselda', position: 'Messenger', salary: '12,092.00', station: 'Office of the SB Secretary' },
  { surname: 'Palmes', firstName: 'Renelyn', position: 'Loc. Leg. Staff Employee', salary: '12,183.00', station: 'Office of the SB Secretary' },
  { surname: 'Lincio', firstName: 'Abner', position: 'Adm. Aide I', salary: '11,473.00', station: 'Office of the SB Secretary' },
  { surname: 'Sangrones', firstName: 'Genalyn', position: 'Adm. Aide I', salary: '11,473.00', station: 'Office of the SB Secretary' },
  { surname: 'Lozada', firstName: 'Heber', position: 'Adm. Aide I', salary: '11,388.00', station: 'Office of the SB Secretary' },
  { surname: 'Labao', firstName: 'Leodegario', position: 'Municipal Mayor', salary: '119,106.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Domingo', firstName: 'Cherry Lyn', position: 'Supply Ofcr. IV', salary: '63,153.00', station: 'Office of the Municipal Mayor (GSO/Supply)' },
  { surname: 'Marabe', firstName: 'Edwin', position: 'Adm. Officer V', salary: '42,287.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Villorente', firstName: 'Kenneth John', position: 'Tourism Opr. Officer', salary: '32,453.00', station: 'Municipal Tourism Office' },
  { surname: 'Lozada', firstName: 'Edgardo', position: 'Comm. Equip Inspr.', salary: '24,636.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Clarite', firstName: 'Jeovy', position: 'Adm. Aide III', salary: '12,843.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Dela Cruz', firstName: 'Kristy', position: 'Adm. Aide II', salary: '12,183.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Lorja', firstName: 'Mary Mae', position: 'Adm. Aide II', salary: '12,183.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Villanueva', firstName: 'Cris', position: 'Adm. Aide I', salary: '11,567.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Silvestre', firstName: 'Nikki', position: 'Adm. Aide I', salary: '11,473.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Delfin', firstName: 'Brenn', position: 'Adm. Aide I', salary: '11,473.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Arteza', firstName: 'Jerce Ann', position: 'Adm. Aide I', salary: '11,473.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Apruebo', firstName: 'Adiel', position: 'Adm. Aide I', salary: '11,473.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Monajan', firstName: 'Sergio', position: 'Adm. Aide I', salary: '11,473.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Salsya', firstName: 'Shiela Marie', position: 'Adm. Aide I', salary: '11,473.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Martinez', firstName: 'Randy Ryan', position: 'Adm. Aide I', salary: '11,473.00', station: 'Office of the Municipal Mayor' },
  { surname: 'Launio', firstName: 'Ma. Angel Adora', position: 'Municipal Accountant', salary: '81,937.00', station: 'Municipal Accounting Office' },
  { surname: 'Valiente', firstName: 'Ma. Bernardith', position: 'Adm. Aide VI', salary: '15,359.00', station: 'Municipal Accounting Office' },
  { surname: 'Lardoc', firstName: 'Honey', position: 'Adm. Aide I', salary: '11,567.00', station: 'Municipal Accounting Office' },
  { surname: 'Llana', firstName: 'Gellne', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Accounting Office' },
  { surname: 'De Domingo', firstName: 'Rodelyn', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Accounting Office' },
  { surname: 'Lunas', firstName: 'Rachris', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Accounting Office' },
  { surname: 'Calsitoro', firstName: 'Kimberly', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Accounting Office' },
  { surname: 'Dila', firstName: 'Gracelyn', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Accounting Office' },
  { surname: 'Andaya', firstName: 'Charlene', position: 'Mun. Assessor', salary: '79,382.00', station: 'Municipal Assessor Office' },
  { surname: 'Laurilla', firstName: 'Princes Diana', position: 'Loc. Asst. Ofcr. I', salary: '24,165.00', station: 'Municipal Assessor Office' },
  { surname: 'Bautista', firstName: 'Juneleen', position: 'Assess. Clerk I', salary: '13,638.00', station: 'Municipal Assessor Office' },
  { surname: 'Feizado', firstName: 'Lilibeth', position: 'Adm. Aide I', salary: '11,662.00', station: 'Municipal Assessor Office' },
  { surname: 'Aleyon', firstName: 'Pablito', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Assessor Office' },
  { surname: 'Sibug', firstName: 'Rose', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Assessor Office' },
  { surname: 'Dela Cruz', firstName: 'Joseph', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Assessor Office' },
  { surname: 'Lusabia', firstName: 'John Paul', position: 'MGDH I', salary: '79,382.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office (MDRRMO)' },
  { surname: 'Bolido', firstName: 'Gerry', position: 'Loc. MDRRM Ofcr. III', salary: '41,410.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office (MDRRMO)' },
  { surname: 'Candido', firstName: 'Mary Rose', position: 'Nurse I', salary: '39,311.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office (MDRRMO)' },
  { surname: 'Alayon', firstName: 'Ma. AJ', position: 'Loc. MDRRM', salary: '17,329.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office (MDRRMO)' },
  { surname: 'Victoriano', firstName: 'Skye', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office (MDRRMO)' },
  { surname: 'Adio', firstName: 'Girlie', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office (MDRRMO)' },
  { surname: 'Degoma', firstName: 'Johanna Mari', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office (MDRRMO)' },
  { surname: 'Gavero', firstName: 'Rowena', position: 'MHO-I', salary: '96,159.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Laysa', firstName: 'Louise Anne', position: 'Nurse V', salary: '61,562.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Ocate', firstName: 'Concepcion', position: 'Nurse IV', salary: '55,907.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Leccio', firstName: 'Cheryl', position: 'Med Tech. I', salary: '31,034.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Lipardo', firstName: 'Criselda', position: 'Midwife II', salary: '31,343.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Gregorio', firstName: 'Felna', position: 'Midwife II', salary: '31,343.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Lompero', firstName: 'Marynelle', position: 'Midwife II', salary: '31,034.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Asis', firstName: 'Marivic', position: 'Midwife II', salary: '29,552.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Andaya', firstName: 'Mylene', position: 'Midwife I', salary: '23,860.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Felosopo', firstName: 'Cazel', position: 'Sanitation Insp. I', salary: '19,612.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Laubeña', firstName: 'Irene', position: 'Sanitation Insp. I', salary: '19,612.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Patriarca', firstName: 'Joy', position: 'Adm. Aide I', salary: '13,899.00', station: 'Municipal Health Office / Rural Health Unit' },
  { surname: 'Salomeo', firstName: 'Nilo', position: 'Mun. Treas.', salary: '79,382.00', station: 'Municipal Treasurers Office' },
  { surname: 'Navarra', firstName: 'Danny', position: 'Loc. Treas. Opr. Off', salary: '24,638.00', station: 'Municipal Treasurers Office' },
  { surname: 'Launio', firstName: 'Cynthia', position: 'Rev. Coll. Clerk I', salary: '14,916.00', station: 'Municipal Treasurers Office' },
  { surname: 'Andaya', firstName: 'Jovelyn', position: 'Rev. Coll. Clerk I', salary: '14,805.00', station: 'Municipal Treasurers Office' },
  { surname: 'Ledesma', firstName: 'Catalino', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Treasurers Office' },
  { surname: 'Fernandez', firstName: 'Jelyn', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Treasurers Office' },
  { surname: 'Navarra', firstName: 'John Vincent', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Treasurers Office' },
  { surname: 'Moises', firstName: 'Alma', position: 'Mun. Budget Officer', salary: '88,659.00', station: 'Municipal Budget Office' },
  { surname: 'Baranda', firstName: 'Kathleen', position: 'Adm. Aide IV', salary: '41,410.00', station: 'Municipal Budget Office' },
  { surname: 'Ledesma', firstName: 'Jay Ann', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Budget Office' },
  { surname: 'Lariosa', firstName: 'Jane May', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Budget Office' },
  { surname: 'Potato', firstName: 'Byron', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Budget Office' },
  { surname: 'Martinez', firstName: 'Erlinda', position: 'Adm. Aide I', salary: '11,662.00', station: 'Municipal Budget Office' },
  { surname: 'Academia', firstName: 'Rosa', position: 'Adm. Aide I', salary: '11,662.00', station: 'Municipal Budget Office' },
  { surname: 'Degallado', firstName: 'Anthony', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Budget Office' },
  { surname: 'Linan', firstName: 'Neda', position: 'Municipal Agriculturist', salary: '81,937.00', station: 'Municipal Agriculture Office' },
  { surname: 'Ayro', firstName: 'Ramon', position: 'Agri. Technologist', salary: '21,657.00', station: 'Municipal Agriculture Office' },
  { surname: 'Javier', firstName: 'Manuel Jr.', position: 'Agri. Technologist', salary: '20,954.00', station: 'Municipal Agriculture Office' },
  { surname: 'Luna', firstName: 'Leonil', position: 'Agri. Technologist', salary: '20,795.00', station: 'Municipal Agriculture Office' },
  { surname: 'Frias', firstName: 'Clark', position: 'Agri. Technologist', salary: '20,795.00', station: 'Municipal Agriculture Office' },
  { surname: 'Borres', firstName: 'Reyna Mae', position: 'Agri. Technologist', salary: '20,627.00', station: 'Municipal Agriculture Office' },
  { surname: 'Vista', firstName: 'Carlito', position: 'Livestock Insp. I', salary: '16,057.00', station: 'Municipal Agriculture Office' },
  { surname: 'Felizardo', firstName: 'Joseph', position: 'Adm. Aide III', salary: '12,843.00', station: 'Municipal Agriculture Office' },
  { surname: 'Luces', firstName: 'Manuel Jr.', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Agriculture Office' },
  { surname: 'Ricalia', firstName: 'Racquel Ann', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Agriculture Office' },
  { surname: 'Solis', firstName: 'Eida', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Agriculture Office' },
  { surname: 'Luces', firstName: 'Liezel', position: 'Adm. Aide I', salary: '11,388.00', station: 'Municipal Agriculture Office' },
  { surname: 'Toledo', firstName: 'Louie', position: 'MPDC', salary: '88,659.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Andaya', firstName: 'Bryan Karl', position: 'MGADH I', salary: '64,074.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Selorio', firstName: 'Joy Denise', position: 'Devt. Officer I', salary: '24,165.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Dela Cena', firstName: 'Analie', position: 'Adm. Officer', salary: '17,486.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Llorito', firstName: 'Kimberly', position: 'Adm. Aide IV', salary: '13,741.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Latiera', firstName: 'Robert', position: 'Adm. Aide I', salary: '11,662.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Berondo', firstName: 'Ryan', position: 'Adm. Aide I', salary: '11,473.00', station: 'Municipal Planning and Development Office' }
];

employeesToUpdate.forEach(emp => {
    const annualSalary = parseFloat(emp.salary.replace(/,/g, '')) * 12;
    console.log(`UPDATE employees SET service_records = jsonb_set(service_records, '{0, designation}', '"${emp.position}"') || jsonb_set(service_records, '{0, station}', '"${emp.station}"') || jsonb_set(service_records, '{0, salary}', '"${emp.salary}"') || jsonb_set(service_records, '{0, annual_salary}', '"${annualSalary.toFixed(2)}"') WHERE surname ILIKE '%${emp.surname}%' AND first_name ILIKE '%${emp.firstName}%';`);
});
