
const employeesToUpdate = [
  { surname: 'Talaban', firstName: 'Babelyn', position: 'MSWDO', annualSalary: '967776.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Lacuarta', firstName: 'Jerry', position: 'Soc. Welfare Asst.', annualSalary: '221472.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Villoza', firstName: 'Pamela', position: 'Soc. Welfare Asst. II', annualSalary: '211740.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Arteza', firstName: 'Jeanny', position: 'Soc. Welfare Aide', annualSalary: '166140.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Laz', firstName: 'Jose', position: 'Adm. Aide III', annualSalary: '155292.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Palomo', firstName: 'Frankie', position: 'Adm. Aide III', annualSalary: '154116.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Diaz', firstName: 'Frank', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Moaña', firstName: 'Neisa', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Mesias', firstName: 'Sallie', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Dela Cruz', firstName: 'Joselito', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Galapia', firstName: 'Jackelyn', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Social Welfare and Development Office' },
  { surname: 'Montorio', firstName: 'Desam', position: 'H.R.M.O V', annualSalary: '952584.00', station: 'Human Resource Management Office' },
  { surname: 'Golez', firstName: 'Maryjean', position: 'Adm. Aide IV', annualSalary: '172476.00', station: 'Human Resource Management Office' },
  { surname: 'Alcjado', firstName: 'Shanie', position: 'Adm. Aide II', annualSalary: '145104.00', station: 'Human Resource Management Office' },
  { surname: 'Baldonado', firstName: 'Joselito', position: 'Adm. Aide I', annualSalary: '139944.00', station: 'Human Resource Management Office' },
  { surname: 'Andaya', firstName: 'Ma. Aurora', position: 'Mun. Civil Registrar', annualSalary: '1014924.00', station: 'Municipal Civil Registrar\'s Office' },
  { surname: 'Mesias', firstName: 'Erlinda', position: 'Messenger', annualSalary: '147288.00', station: 'Municipal Civil Registrar\'s Office' },
  { surname: 'Gregore', firstName: 'Erly', position: 'Adm. Aide I', annualSalary: '138804.00', station: 'Municipal Civil Registrar\'s Office' },
  { surname: 'Labo', firstName: 'Sharon', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Civil Registrar\'s Office' },
  { surname: 'Leonardo', firstName: 'Irene', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Civil Registrar\'s Office' },
  { surname: 'Letran', firstName: 'Angel', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Civil Registrar\'s Office' },
  { surname: 'Labo', firstName: 'Alejandre', position: 'Mun. Engineer', annualSalary: '1063908.00', station: 'Municipal Engineering Office' },
  { surname: 'Labao', firstName: 'Rexjhon', position: 'MGADH I', annualSalary: '757836.00', station: 'Municipal Engineering Office' },
  { surname: 'Berganio', firstName: 'Karen', position: 'Engineer III', annualSalary: '546180.00', station: 'Municipal Engineering Office' },
  { surname: 'Toledo', firstName: 'Gerbert', position: 'Gen. Foreman', annualSalary: '209952.00', station: 'Municipal Engineering Office' },
  { surname: 'Guion', firstName: 'Gerold', position: 'Adm. Aide I', annualSalary: '143412.00', station: 'Municipal Engineering Office' },
  { surname: 'Villareal', firstName: 'Gemma', position: 'Adm. Aide I', annualSalary: '143412.00', station: 'Municipal Engineering Office' },
  { surname: 'Puncion', firstName: 'Josephine', position: 'Adm. Aide I', annualSalary: '139944.00', station: 'Municipal Engineering Office' },
  { surname: 'Leno', firstName: 'Luna Rose', position: 'Adm. Aide I', annualSalary: '138804.00', station: 'Municipal Engineering Office' },
  { surname: 'Guatio', firstName: 'Rhodora', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Engineering Office' },
  { surname: 'Magbanua', firstName: 'Noe', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Engineering Office' },
  { surname: 'Osias', firstName: 'Ferdinand', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Engineering Office' },
  { surname: 'Gallardo', firstName: 'Amie', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Engineering Office' },
  { surname: 'Barte', firstName: 'Michel', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Engineering Office' },
  { surname: 'Ocbeña', firstName: 'Darenne', position: 'Adm. Aide I', annualSalary: '142248.00', station: 'General Services / Admin' },
  { surname: 'Crisostomo', firstName: 'Mila', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'General Services / Admin' },
  { surname: 'Gregorio', firstName: 'Mica', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'General Services / Admin' },
  { surname: 'Lago', firstName: 'Teresa', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'General Services / Admin' },
  { surname: 'Buenavista', firstName: 'Richard', position: 'Mun. Vice Mayor', annualSalary: '1084404.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Labao', firstName: 'Mary Ann', position: 'S. B. Member', annualSalary: '967776.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Villiester', firstName: 'Catherine', position: 'S. B. Member', annualSalary: '967776.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Ticer', firstName: 'Raul', position: 'S. B. Member', annualSalary: '952584.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Laurilla', firstName: 'John', position: 'S. B. Member', annualSalary: '952584.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Trajano', firstName: 'Fatima', position: 'S. B. Member', annualSalary: '952584.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Layo', firstName: 'Jeffrey', position: 'S. B. Member', annualSalary: '952584.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Jumbas', firstName: 'Joefred sheen', position: 'S. B. Member', annualSalary: '952584.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Uy', firstName: 'Maria Rhodora', position: 'S. B. Member', annualSalary: '967776.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Quincy', firstName: 'George', position: 'ABC President', annualSalary: '952584.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Buenavista', firstName: 'Frederick Ruis', position: 'SK President', annualSalary: '952584.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Leonida', firstName: 'Jerry', position: 'SB Secretary', annualSalary: '1063908.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Bersurto', firstName: 'Irish Ann', position: 'Local Leg Staff Officer IV', annualSalary: '546180.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Puncion', firstName: 'Che-An', position: 'Local Leg Staff Officer I', annualSalary: '333324.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Ladoc', firstName: 'Mariane', position: 'Loc. Leg. Staff Asst. III', annualSalary: '292788.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Benjamin', firstName: 'Vincent', position: 'Loc. Leg. Staff Asst. I', annualSalary: '249540.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Benjamin', firstName: 'Ma. Cenneth', position: 'Loc. Leg. Staff Employee', annualSalary: '184308.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Canique', firstName: 'Jinalyn', position: 'Loc. Leg. Staff Employee', annualSalary: '164892.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Llorente', firstName: 'Christine Joy', position: 'Adm. aide III', annualSalary: '155292.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Vpinosa', firstName: 'Levi', position: 'Adm. aide III', annualSalary: '155292.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Labao', firstName: 'Hazel', position: 'Local Leg. Staff Employee', annualSalary: '148404.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Labris', firstName: 'Jesa', position: 'Messenger', annualSalary: '147288.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Palma', firstName: 'Criselda', position: 'Messenger', annualSalary: '145104.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Palmes', firstName: 'Renelyn', position: 'Loc. Leg. Staff Employee', annualSalary: '146196.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Lincio', firstName: 'Abner', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Sangrones', firstName: 'Genalyn', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Lozada', firstName: 'Heber', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Sangguniang Bayan Office' },
  { surname: 'Labao', firstName: 'Leodegario', position: 'Municipal Mayor', annualSalary: '1429272.00', station: 'Mayor\'s Office' },
  { surname: 'Domingo', firstName: 'Cherry Lyn', position: 'Supply Ofcr. IV', annualSalary: '757836.00', station: 'Mayor\'s Office' },
  { surname: 'Marabe', firstName: 'Edwin', position: 'Adm. Officer V', annualSalary: '507444.00', station: 'Mayor\'s Office' },
  { surname: 'Villorente', firstName: 'Kenneth John', position: 'Tourism Opr. Officer', annualSalary: '389436.00', station: 'Mayor\'s Office' },
  { surname: 'Lozada', firstName: 'Edgardo', position: 'Comm. Equip Inspr.', annualSalary: '295632.00', station: 'Mayor\'s Office' },
  { surname: 'Clarite', firstName: 'Jeovy', position: 'Adm. Aide III', annualSalary: '154116.00', station: 'Mayor\'s Office' },
  { surname: 'Dela Cruz', firstName: 'Kristy', position: 'Adm. Aide II', annualSalary: '146196.00', station: 'Mayor\'s Office' },
  { surname: 'Lorja', firstName: 'Mary Mae', position: 'Adm. Aide II', annualSalary: '146196.00', station: 'Mayor\'s Office' },
  { surname: 'Villanueva', firstName: 'Cris', position: 'Adm. Aide I', annualSalary: '138804.00', station: 'Mayor\'s Office' },
  { surname: 'Silvestre', firstName: 'Nikki', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Mayor\'s Office' },
  { surname: 'Delfin', firstName: 'Brenn', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Mayor\'s Office' },
  { surname: 'Arteza', firstName: 'Jerce Ann', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Mayor\'s Office' },
  { surname: 'Apruebo', firstName: 'Adiel', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Mayor\'s Office' },
  { surname: 'Monajan', firstName: 'Sergio', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Mayor\'s Office' },
  { surname: 'Salsya', firstName: 'Shiela Marie', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Mayor\'s Office' },
  { surname: 'Martinez', firstName: 'Randy Ryan', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Mayor\'s Office' },
  { surname: 'Launio', firstName: 'Ma. Angel Adora', position: 'Municipal Accountant', annualSalary: '983244.00', station: 'Municipal Accounting Office' },
  { surname: 'Valiente', firstName: 'Ma. Bernardith', position: 'Adm. Aide VI', annualSalary: '184308.00', station: 'Municipal Accounting Office' },
  { surname: 'Lardoc', firstName: 'Honey', position: 'Adm. Aide I', annualSalary: '138804.00', station: 'Municipal Accounting Office' },
  { surname: 'Llana', firstName: 'Gellne', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Accounting Office' },
  { surname: 'De Domingo', firstName: 'Rodelyn', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Accounting Office' },
  { surname: 'Lunas', firstName: 'Rachris', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Accounting Office' },
  { surname: 'Calsitoro', firstName: 'Kimberly', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Accounting Office' },
  { surname: 'Dila', firstName: 'Gracelyn', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Accounting Office' },
  { surname: 'Andaya', firstName: 'Charlene', position: 'Mun. Assessor', annualSalary: '952584.00', station: 'Municipal Assessor\'s Office' },
  { surname: 'Laurilla', firstName: 'Princes Diana', position: 'Loc. Asst. Ofcr. I', annualSalary: '289980.00', station: 'Municipal Assessor\'s Office' },
  { surname: 'Bautista', firstName: 'Juneleen', position: 'Assess. Clerk I', annualSalary: '163656.00', station: 'Municipal Assessor\'s Office' },
  { surname: 'Feizado', firstName: 'Lilibeth', position: 'Adm. Aide I', annualSalary: '139944.00', station: 'Municipal Assessor\'s Office' },
  { surname: 'Aleyon', firstName: 'Pablito', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Assessor\'s Office' },
  { surname: 'Sibug', firstName: 'Rose', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Assessor\'s Office' },
  { surname: 'Dela Cruz', firstName: 'Joseph', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Assessor\'s Office' },
  { surname: 'Lusabia', firstName: 'John Paul', position: 'MGDH I', annualSalary: '952584.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office' },
  { surname: 'Bolido', firstName: 'Gerry', position: 'Loc. MDRRM Ofcr. III', annualSalary: '496920.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office' },
  { surname: 'Candido', firstName: 'Mary Rose', position: 'Nurse I', annualSalary: '471732.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office' },
  { surname: 'Alayon', firstName: 'Ma. AJ', position: 'Loc. MDRRM', annualSalary: '207948.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office' },
  { surname: 'Victoriano', firstName: 'Skye', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office' },
  { surname: 'Adio', firstName: 'Girlie', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office' },
  { surname: 'Degoma', firstName: 'Johanna Mari', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Disaster Risk Reduction & Mgmt Office' },
  { surname: 'Gavero', firstName: 'Rowena', position: 'MHO-I', annualSalary: '1153908.00', station: 'Municipal Health Office' },
  { surname: 'Laysa', firstName: 'Louise Anne', position: 'Nurse V', annualSalary: '738744.00', station: 'Municipal Health Office' },
  { surname: 'Ocate', firstName: 'Concepcion', position: 'Nurse IV', annualSalary: '670884.00', station: 'Municipal Health Office' },
  { surname: 'Leccio', firstName: 'Cheryl', position: 'Med Tech. I', annualSalary: '372408.00', station: 'Municipal Health Office' },
  { surname: 'Lipardo', firstName: 'Criselda', position: 'Midwife II', annualSalary: '376116.00', station: 'Municipal Health Office' },
  { surname: 'Gregorio', firstName: 'Felna', position: 'Midwife II', annualSalary: '376116.00', station: 'Municipal Health Office' },
  { surname: 'Lompero', firstName: 'Marynelle', position: 'Midwife II', annualSalary: '372408.00', station: 'Municipal Health Office' },
  { surname: 'Asis', firstName: 'Marivic', position: 'Midwife II', annualSalary: '354624.00', station: 'Municipal Health Office' },
  { surname: 'Andaya', firstName: 'Mylene', position: 'Midwife I', annualSalary: '286320.00', station: 'Municipal Health Office' },
  { surname: 'Felosopo', firstName: 'Cazel', position: 'Sanitation Insp. I', annualSalary: '235344.00', station: 'Municipal Health Office' },
  { surname: 'Laubeña', firstName: 'Irene', position: 'Sanitation Insp. I', annualSalary: '235344.00', station: 'Municipal Health Office' },
  { surname: 'Patriarca', firstName: 'Joy', position: 'Adm. Aide I', annualSalary: '166788.00', station: 'Municipal Health Office' },
  { surname: 'Salomeo', firstName: 'Nilo', position: 'Mun. Treas.', annualSalary: '952584.00', station: 'Municipal Treasurer\'s Office' },
  { surname: 'Navarra', firstName: 'Danny', position: 'Loc. Treas. Opr. Off', annualSalary: '295656.00', station: 'Municipal Treasurer\'s Office' },
  { surname: 'Launio', firstName: 'Cynthia', position: 'Rev. Coll. Clerk I', annualSalary: '178992.00', station: 'Municipal Treasurer\'s Office' },
  { surname: 'Andaya', firstName: 'Jovelyn', position: 'Rev. Coll. Clerk I', annualSalary: '177660.00', station: 'Municipal Treasurer\'s Office' },
  { surname: 'Ledesma', firstName: 'Catalino', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Treasurer\'s Office' },
  { surname: 'Fernandez', firstName: 'Jelyn', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Treasurer\'s Office' },
  { surname: 'Navarra', firstName: 'John Vincent', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Treasurer\'s Office' },
  { surname: 'Moises', firstName: 'Alma', position: 'Mun. Budget Officer', annualSalary: '1063908.00', station: 'Municipal Budget Office' },
  { surname: 'Baranda', firstName: 'Kathleen', position: 'Adm. Aide IV', annualSalary: '496920.00', station: 'Municipal Budget Office' },
  { surname: 'Ledesma', firstName: 'Jay Ann', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Budget Office' },
  { surname: 'Lariosa', firstName: 'Jane May', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Budget Office' },
  { surname: 'Potato', firstName: 'Byron', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Budget Office' },
  { surname: 'Martinez', firstName: 'Erlinda', position: 'Adm. Aide I', annualSalary: '139944.00', station: 'Municipal Budget Office' },
  { surname: 'Academia', firstName: 'Rosa', position: 'Adm. Aide I', annualSalary: '139944.00', station: 'Municipal Budget Office' },
  { surname: 'Degallado', firstName: 'Anthony', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Budget Office' },
  { surname: 'Linan', firstName: 'Neda', position: 'Municipal Agriculturist', annualSalary: '983244.00', station: 'Municipal Agriculture Office' },
  { surname: 'Ayro', firstName: 'Ramon', position: 'Agri. Technologist', annualSalary: '259884.00', station: 'Municipal Agriculture Office' },
  { surname: 'Javier', firstName: 'Manuel Jr.', position: 'Agri. Technologist', annualSalary: '251448.00', station: 'Municipal Agriculture Office' },
  { surname: 'Luna', firstName: 'Leonil', position: 'Agri. Technologist', annualSalary: '249540.00', station: 'Municipal Agriculture Office' },
  { surname: 'Frias', firstName: 'Clark', position: 'Agri. Technologist', annualSalary: '249540.00', station: 'Municipal Agriculture Office' },
  { surname: 'Borres', firstName: 'Reyna Mae', position: 'Agri. Technologist', annualSalary: '247524.00', station: 'Municipal Agriculture Office' },
  { surname: 'Vista', firstName: 'Carlito', position: 'Livestock Insp. I', annualSalary: '192684.00', station: 'Municipal Agriculture Office' },
  { surname: 'Felizardo', firstName: 'Joseph', position: 'Adm. Aide III', annualSalary: '154116.00', station: 'Municipal Agriculture Office' },
  { surname: 'Luces', firstName: 'Manuel Jr.', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Agriculture Office' },
  { surname: 'Ricalia', firstName: 'Racquel Ann', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Agriculture Office' },
  { surname: 'Solis', firstName: 'Eida', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Agriculture Office' },
  { surname: 'Luces', firstName: 'Liezel', position: 'Adm. Aide I', annualSalary: '136656.00', station: 'Municipal Agriculture Office' },
  { surname: 'Toledo', firstName: 'Louie', position: 'MPDC', annualSalary: '1063908.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Andaya', firstName: 'Bryan Karl', position: 'MGADH I', annualSalary: '768888.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Selorio', firstName: 'Joy Denise', position: 'Devt. Officer I', annualSalary: '289980.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Dela Cena', firstName: 'Analie', position: 'Adm. Officer', annualSalary: '209832.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Llorito', firstName: 'Kimberly', position: 'Adm. Aide IV', annualSalary: '164892.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Latiera', firstName: 'Robert', position: 'Adm. Aide I', annualSalary: '139944.00', station: 'Municipal Planning and Development Office' },
  { surname: 'Berondo', firstName: 'Ryan', position: 'Adm. Aide I', annualSalary: '137676.00', station: 'Municipal Planning and Development Office' }
];

employeesToUpdate.forEach(emp => {
    // We clean the annual salary to just numeric string
    const annualSalary = emp.annualSalary.replace(/[^0-9.]/g, '');
    const monthlySalary = (parseFloat(annualSalary) / 12).toFixed(2);
    
    // We use the ID to specifically target the records we want to update. 
    // Wait, the SQL update relies on name, not ID. That might be the issue if there are multiple similar names.
    // Let's use a unique identifier or update the ID if possible.
    // For now, continue using name but be very careful.
    
    console.log(`UPDATE employees SET service_records = '[{"id": "sr-fixed-${emp.surname.replace(/ /g,'')}-${emp.firstName.replace(/ /g,'')}", "to": "Present", "from": "2016-07-01", "salary": "${monthlySalary}", "annual_salary": "${annualSalary}", "station": "${emp.station}", "designation": "${emp.position}", "status": "Permanent"}]'::jsonb WHERE surname ILIKE '%${emp.surname}%' AND first_name ILIKE '%${emp.firstName}%';`);
});
